// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/photos/types/media_item.proto

package com.google.photos.types.proto;

/**
 *
 *
 * <pre>
 * Metadata for a media item.
 * </pre>
 *
 * Protobuf type {@code google.photos.types.MediaMetadata}
 */
public final class MediaMetadata extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.photos.types.MediaMetadata)
    MediaMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use MediaMetadata.newBuilder() to construct.
  private MediaMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private MediaMetadata() {}

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new MediaMetadata();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.photos.types.proto.MediaItemProto
        .internal_static_google_photos_types_MediaMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.photos.types.proto.MediaItemProto
        .internal_static_google_photos_types_MediaMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.photos.types.proto.MediaMetadata.class,
            com.google.photos.types.proto.MediaMetadata.Builder.class);
  }

  private int metadataCase_ = 0;
  private java.lang.Object metadata_;

  public enum MetadataCase
      implements
          com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PHOTO(6),
    VIDEO(7),
    METADATA_NOT_SET(0);
    private final int value;

    private MetadataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MetadataCase valueOf(int value) {
      return forNumber(value);
    }

    public static MetadataCase forNumber(int value) {
      switch (value) {
        case 6:
          return PHOTO;
        case 7:
          return VIDEO;
        case 0:
          return METADATA_NOT_SET;
        default:
          return null;
      }
    }

    public int getNumber() {
      return this.value;
    }
  };

  public MetadataCase getMetadataCase() {
    return MetadataCase.forNumber(metadataCase_);
  }

  public static final int CREATION_TIME_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp creationTime_;
  /**
   *
   *
   * <pre>
   * Time when the media item was first created (not when it was uploaded to
   * Google Photos).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp creation_time = 1;</code>
   *
   * @return Whether the creationTime field is set.
   */
  @java.lang.Override
  public boolean hasCreationTime() {
    return creationTime_ != null;
  }
  /**
   *
   *
   * <pre>
   * Time when the media item was first created (not when it was uploaded to
   * Google Photos).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp creation_time = 1;</code>
   *
   * @return The creationTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreationTime() {
    return creationTime_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : creationTime_;
  }
  /**
   *
   *
   * <pre>
   * Time when the media item was first created (not when it was uploaded to
   * Google Photos).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp creation_time = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreationTimeOrBuilder() {
    return creationTime_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : creationTime_;
  }

  public static final int WIDTH_FIELD_NUMBER = 2;
  private long width_ = 0L;
  /**
   *
   *
   * <pre>
   * Original width (in pixels) of the media item.
   * </pre>
   *
   * <code>int64 width = 2;</code>
   *
   * @return The width.
   */
  @java.lang.Override
  public long getWidth() {
    return width_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 3;
  private long height_ = 0L;
  /**
   *
   *
   * <pre>
   * Original height (in pixels) of the media item.
   * </pre>
   *
   * <code>int64 height = 3;</code>
   *
   * @return The height.
   */
  @java.lang.Override
  public long getHeight() {
    return height_;
  }

  public static final int PHOTO_FIELD_NUMBER = 6;
  /**
   *
   *
   * <pre>
   * Metadata for a photo media type.
   * </pre>
   *
   * <code>.google.photos.types.Photo photo = 6;</code>
   *
   * @return Whether the photo field is set.
   */
  @java.lang.Override
  public boolean hasPhoto() {
    return metadataCase_ == 6;
  }
  /**
   *
   *
   * <pre>
   * Metadata for a photo media type.
   * </pre>
   *
   * <code>.google.photos.types.Photo photo = 6;</code>
   *
   * @return The photo.
   */
  @java.lang.Override
  public com.google.photos.types.proto.Photo getPhoto() {
    if (metadataCase_ == 6) {
      return (com.google.photos.types.proto.Photo) metadata_;
    }
    return com.google.photos.types.proto.Photo.getDefaultInstance();
  }
  /**
   *
   *
   * <pre>
   * Metadata for a photo media type.
   * </pre>
   *
   * <code>.google.photos.types.Photo photo = 6;</code>
   */
  @java.lang.Override
  public com.google.photos.types.proto.PhotoOrBuilder getPhotoOrBuilder() {
    if (metadataCase_ == 6) {
      return (com.google.photos.types.proto.Photo) metadata_;
    }
    return com.google.photos.types.proto.Photo.getDefaultInstance();
  }

  public static final int VIDEO_FIELD_NUMBER = 7;
  /**
   *
   *
   * <pre>
   * Metadata for a video media type.
   * </pre>
   *
   * <code>.google.photos.types.Video video = 7;</code>
   *
   * @return Whether the video field is set.
   */
  @java.lang.Override
  public boolean hasVideo() {
    return metadataCase_ == 7;
  }
  /**
   *
   *
   * <pre>
   * Metadata for a video media type.
   * </pre>
   *
   * <code>.google.photos.types.Video video = 7;</code>
   *
   * @return The video.
   */
  @java.lang.Override
  public com.google.photos.types.proto.Video getVideo() {
    if (metadataCase_ == 7) {
      return (com.google.photos.types.proto.Video) metadata_;
    }
    return com.google.photos.types.proto.Video.getDefaultInstance();
  }
  /**
   *
   *
   * <pre>
   * Metadata for a video media type.
   * </pre>
   *
   * <code>.google.photos.types.Video video = 7;</code>
   */
  @java.lang.Override
  public com.google.photos.types.proto.VideoOrBuilder getVideoOrBuilder() {
    if (metadataCase_ == 7) {
      return (com.google.photos.types.proto.Video) metadata_;
    }
    return com.google.photos.types.proto.Video.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (creationTime_ != null) {
      output.writeMessage(1, getCreationTime());
    }
    if (width_ != 0L) {
      output.writeInt64(2, width_);
    }
    if (height_ != 0L) {
      output.writeInt64(3, height_);
    }
    if (metadataCase_ == 6) {
      output.writeMessage(6, (com.google.photos.types.proto.Photo) metadata_);
    }
    if (metadataCase_ == 7) {
      output.writeMessage(7, (com.google.photos.types.proto.Video) metadata_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (creationTime_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getCreationTime());
    }
    if (width_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, width_);
    }
    if (height_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, height_);
    }
    if (metadataCase_ == 6) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              6, (com.google.photos.types.proto.Photo) metadata_);
    }
    if (metadataCase_ == 7) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              7, (com.google.photos.types.proto.Video) metadata_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.photos.types.proto.MediaMetadata)) {
      return super.equals(obj);
    }
    com.google.photos.types.proto.MediaMetadata other =
        (com.google.photos.types.proto.MediaMetadata) obj;

    if (hasCreationTime() != other.hasCreationTime()) return false;
    if (hasCreationTime()) {
      if (!getCreationTime().equals(other.getCreationTime())) return false;
    }
    if (getWidth() != other.getWidth()) return false;
    if (getHeight() != other.getHeight()) return false;
    if (!getMetadataCase().equals(other.getMetadataCase())) return false;
    switch (metadataCase_) {
      case 6:
        if (!getPhoto().equals(other.getPhoto())) return false;
        break;
      case 7:
        if (!getVideo().equals(other.getVideo())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCreationTime()) {
      hash = (37 * hash) + CREATION_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreationTime().hashCode();
    }
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getWidth());
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getHeight());
    switch (metadataCase_) {
      case 6:
        hash = (37 * hash) + PHOTO_FIELD_NUMBER;
        hash = (53 * hash) + getPhoto().hashCode();
        break;
      case 7:
        hash = (37 * hash) + VIDEO_FIELD_NUMBER;
        hash = (53 * hash) + getVideo().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaMetadata parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.photos.types.proto.MediaMetadata parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.photos.types.proto.MediaMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.photos.types.proto.MediaMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Metadata for a media item.
   * </pre>
   *
   * Protobuf type {@code google.photos.types.MediaMetadata}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.photos.types.MediaMetadata)
      com.google.photos.types.proto.MediaMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.photos.types.proto.MediaItemProto
          .internal_static_google_photos_types_MediaMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.photos.types.proto.MediaItemProto
          .internal_static_google_photos_types_MediaMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.photos.types.proto.MediaMetadata.class,
              com.google.photos.types.proto.MediaMetadata.Builder.class);
    }

    // Construct using com.google.photos.types.proto.MediaMetadata.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      creationTime_ = null;
      if (creationTimeBuilder_ != null) {
        creationTimeBuilder_.dispose();
        creationTimeBuilder_ = null;
      }
      width_ = 0L;
      height_ = 0L;
      if (photoBuilder_ != null) {
        photoBuilder_.clear();
      }
      if (videoBuilder_ != null) {
        videoBuilder_.clear();
      }
      metadataCase_ = 0;
      metadata_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.photos.types.proto.MediaItemProto
          .internal_static_google_photos_types_MediaMetadata_descriptor;
    }

    @java.lang.Override
    public com.google.photos.types.proto.MediaMetadata getDefaultInstanceForType() {
      return com.google.photos.types.proto.MediaMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.photos.types.proto.MediaMetadata build() {
      com.google.photos.types.proto.MediaMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.photos.types.proto.MediaMetadata buildPartial() {
      com.google.photos.types.proto.MediaMetadata result =
          new com.google.photos.types.proto.MediaMetadata(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.photos.types.proto.MediaMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.creationTime_ =
            creationTimeBuilder_ == null ? creationTime_ : creationTimeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.width_ = width_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.height_ = height_;
      }
    }

    private void buildPartialOneofs(com.google.photos.types.proto.MediaMetadata result) {
      result.metadataCase_ = metadataCase_;
      result.metadata_ = this.metadata_;
      if (metadataCase_ == 6 && photoBuilder_ != null) {
        result.metadata_ = photoBuilder_.build();
      }
      if (metadataCase_ == 7 && videoBuilder_ != null) {
        result.metadata_ = videoBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.photos.types.proto.MediaMetadata) {
        return mergeFrom((com.google.photos.types.proto.MediaMetadata) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.photos.types.proto.MediaMetadata other) {
      if (other == com.google.photos.types.proto.MediaMetadata.getDefaultInstance()) return this;
      if (other.hasCreationTime()) {
        mergeCreationTime(other.getCreationTime());
      }
      if (other.getWidth() != 0L) {
        setWidth(other.getWidth());
      }
      if (other.getHeight() != 0L) {
        setHeight(other.getHeight());
      }
      switch (other.getMetadataCase()) {
        case PHOTO:
          {
            mergePhoto(other.getPhoto());
            break;
          }
        case VIDEO:
          {
            mergeVideo(other.getVideo());
            break;
          }
        case METADATA_NOT_SET:
          {
            break;
          }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                input.readMessage(getCreationTimeFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 16:
              {
                width_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
            case 24:
              {
                height_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
            case 50:
              {
                input.readMessage(getPhotoFieldBuilder().getBuilder(), extensionRegistry);
                metadataCase_ = 6;
                break;
              } // case 50
            case 58:
              {
                input.readMessage(getVideoFieldBuilder().getBuilder(), extensionRegistry);
                metadataCase_ = 7;
                break;
              } // case 58
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int metadataCase_ = 0;
    private java.lang.Object metadata_;

    public MetadataCase getMetadataCase() {
      return MetadataCase.forNumber(metadataCase_);
    }

    public Builder clearMetadata() {
      metadataCase_ = 0;
      metadata_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.Timestamp creationTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        creationTimeBuilder_;
    /**
     *
     *
     * <pre>
     * Time when the media item was first created (not when it was uploaded to
     * Google Photos).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 1;</code>
     *
     * @return Whether the creationTime field is set.
     */
    public boolean hasCreationTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     *
     *
     * <pre>
     * Time when the media item was first created (not when it was uploaded to
     * Google Photos).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 1;</code>
     *
     * @return The creationTime.
     */
    public com.google.protobuf.Timestamp getCreationTime() {
      if (creationTimeBuilder_ == null) {
        return creationTime_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : creationTime_;
      } else {
        return creationTimeBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Time when the media item was first created (not when it was uploaded to
     * Google Photos).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 1;</code>
     */
    public Builder setCreationTime(com.google.protobuf.Timestamp value) {
      if (creationTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        creationTime_ = value;
      } else {
        creationTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Time when the media item was first created (not when it was uploaded to
     * Google Photos).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 1;</code>
     */
    public Builder setCreationTime(com.google.protobuf.Timestamp.Builder builderForValue) {
      if (creationTimeBuilder_ == null) {
        creationTime_ = builderForValue.build();
      } else {
        creationTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Time when the media item was first created (not when it was uploaded to
     * Google Photos).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 1;</code>
     */
    public Builder mergeCreationTime(com.google.protobuf.Timestamp value) {
      if (creationTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)
            && creationTime_ != null
            && creationTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreationTimeBuilder().mergeFrom(value);
        } else {
          creationTime_ = value;
        }
      } else {
        creationTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Time when the media item was first created (not when it was uploaded to
     * Google Photos).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 1;</code>
     */
    public Builder clearCreationTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      creationTime_ = null;
      if (creationTimeBuilder_ != null) {
        creationTimeBuilder_.dispose();
        creationTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Time when the media item was first created (not when it was uploaded to
     * Google Photos).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreationTimeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCreationTimeFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Time when the media item was first created (not when it was uploaded to
     * Google Photos).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreationTimeOrBuilder() {
      if (creationTimeBuilder_ != null) {
        return creationTimeBuilder_.getMessageOrBuilder();
      } else {
        return creationTime_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : creationTime_;
      }
    }
    /**
     *
     *
     * <pre>
     * Time when the media item was first created (not when it was uploaded to
     * Google Photos).
     * </pre>
     *
     * <code>.google.protobuf.Timestamp creation_time = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        getCreationTimeFieldBuilder() {
      if (creationTimeBuilder_ == null) {
        creationTimeBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp,
                com.google.protobuf.Timestamp.Builder,
                com.google.protobuf.TimestampOrBuilder>(
                getCreationTime(), getParentForChildren(), isClean());
        creationTime_ = null;
      }
      return creationTimeBuilder_;
    }

    private long width_;
    /**
     *
     *
     * <pre>
     * Original width (in pixels) of the media item.
     * </pre>
     *
     * <code>int64 width = 2;</code>
     *
     * @return The width.
     */
    @java.lang.Override
    public long getWidth() {
      return width_;
    }
    /**
     *
     *
     * <pre>
     * Original width (in pixels) of the media item.
     * </pre>
     *
     * <code>int64 width = 2;</code>
     *
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(long value) {

      width_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Original width (in pixels) of the media item.
     * </pre>
     *
     * <code>int64 width = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      bitField0_ = (bitField0_ & ~0x00000002);
      width_ = 0L;
      onChanged();
      return this;
    }

    private long height_;
    /**
     *
     *
     * <pre>
     * Original height (in pixels) of the media item.
     * </pre>
     *
     * <code>int64 height = 3;</code>
     *
     * @return The height.
     */
    @java.lang.Override
    public long getHeight() {
      return height_;
    }
    /**
     *
     *
     * <pre>
     * Original height (in pixels) of the media item.
     * </pre>
     *
     * <code>int64 height = 3;</code>
     *
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {

      height_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Original height (in pixels) of the media item.
     * </pre>
     *
     * <code>int64 height = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000004);
      height_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.photos.types.proto.Photo,
            com.google.photos.types.proto.Photo.Builder,
            com.google.photos.types.proto.PhotoOrBuilder>
        photoBuilder_;
    /**
     *
     *
     * <pre>
     * Metadata for a photo media type.
     * </pre>
     *
     * <code>.google.photos.types.Photo photo = 6;</code>
     *
     * @return Whether the photo field is set.
     */
    @java.lang.Override
    public boolean hasPhoto() {
      return metadataCase_ == 6;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a photo media type.
     * </pre>
     *
     * <code>.google.photos.types.Photo photo = 6;</code>
     *
     * @return The photo.
     */
    @java.lang.Override
    public com.google.photos.types.proto.Photo getPhoto() {
      if (photoBuilder_ == null) {
        if (metadataCase_ == 6) {
          return (com.google.photos.types.proto.Photo) metadata_;
        }
        return com.google.photos.types.proto.Photo.getDefaultInstance();
      } else {
        if (metadataCase_ == 6) {
          return photoBuilder_.getMessage();
        }
        return com.google.photos.types.proto.Photo.getDefaultInstance();
      }
    }
    /**
     *
     *
     * <pre>
     * Metadata for a photo media type.
     * </pre>
     *
     * <code>.google.photos.types.Photo photo = 6;</code>
     */
    public Builder setPhoto(com.google.photos.types.proto.Photo value) {
      if (photoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        photoBuilder_.setMessage(value);
      }
      metadataCase_ = 6;
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a photo media type.
     * </pre>
     *
     * <code>.google.photos.types.Photo photo = 6;</code>
     */
    public Builder setPhoto(com.google.photos.types.proto.Photo.Builder builderForValue) {
      if (photoBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        photoBuilder_.setMessage(builderForValue.build());
      }
      metadataCase_ = 6;
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a photo media type.
     * </pre>
     *
     * <code>.google.photos.types.Photo photo = 6;</code>
     */
    public Builder mergePhoto(com.google.photos.types.proto.Photo value) {
      if (photoBuilder_ == null) {
        if (metadataCase_ == 6
            && metadata_ != com.google.photos.types.proto.Photo.getDefaultInstance()) {
          metadata_ =
              com.google.photos.types.proto.Photo.newBuilder(
                      (com.google.photos.types.proto.Photo) metadata_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        if (metadataCase_ == 6) {
          photoBuilder_.mergeFrom(value);
        } else {
          photoBuilder_.setMessage(value);
        }
      }
      metadataCase_ = 6;
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a photo media type.
     * </pre>
     *
     * <code>.google.photos.types.Photo photo = 6;</code>
     */
    public Builder clearPhoto() {
      if (photoBuilder_ == null) {
        if (metadataCase_ == 6) {
          metadataCase_ = 0;
          metadata_ = null;
          onChanged();
        }
      } else {
        if (metadataCase_ == 6) {
          metadataCase_ = 0;
          metadata_ = null;
        }
        photoBuilder_.clear();
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a photo media type.
     * </pre>
     *
     * <code>.google.photos.types.Photo photo = 6;</code>
     */
    public com.google.photos.types.proto.Photo.Builder getPhotoBuilder() {
      return getPhotoFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Metadata for a photo media type.
     * </pre>
     *
     * <code>.google.photos.types.Photo photo = 6;</code>
     */
    @java.lang.Override
    public com.google.photos.types.proto.PhotoOrBuilder getPhotoOrBuilder() {
      if ((metadataCase_ == 6) && (photoBuilder_ != null)) {
        return photoBuilder_.getMessageOrBuilder();
      } else {
        if (metadataCase_ == 6) {
          return (com.google.photos.types.proto.Photo) metadata_;
        }
        return com.google.photos.types.proto.Photo.getDefaultInstance();
      }
    }
    /**
     *
     *
     * <pre>
     * Metadata for a photo media type.
     * </pre>
     *
     * <code>.google.photos.types.Photo photo = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.photos.types.proto.Photo,
            com.google.photos.types.proto.Photo.Builder,
            com.google.photos.types.proto.PhotoOrBuilder>
        getPhotoFieldBuilder() {
      if (photoBuilder_ == null) {
        if (!(metadataCase_ == 6)) {
          metadata_ = com.google.photos.types.proto.Photo.getDefaultInstance();
        }
        photoBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.photos.types.proto.Photo,
                com.google.photos.types.proto.Photo.Builder,
                com.google.photos.types.proto.PhotoOrBuilder>(
                (com.google.photos.types.proto.Photo) metadata_, getParentForChildren(), isClean());
        metadata_ = null;
      }
      metadataCase_ = 6;
      onChanged();
      return photoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.photos.types.proto.Video,
            com.google.photos.types.proto.Video.Builder,
            com.google.photos.types.proto.VideoOrBuilder>
        videoBuilder_;
    /**
     *
     *
     * <pre>
     * Metadata for a video media type.
     * </pre>
     *
     * <code>.google.photos.types.Video video = 7;</code>
     *
     * @return Whether the video field is set.
     */
    @java.lang.Override
    public boolean hasVideo() {
      return metadataCase_ == 7;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a video media type.
     * </pre>
     *
     * <code>.google.photos.types.Video video = 7;</code>
     *
     * @return The video.
     */
    @java.lang.Override
    public com.google.photos.types.proto.Video getVideo() {
      if (videoBuilder_ == null) {
        if (metadataCase_ == 7) {
          return (com.google.photos.types.proto.Video) metadata_;
        }
        return com.google.photos.types.proto.Video.getDefaultInstance();
      } else {
        if (metadataCase_ == 7) {
          return videoBuilder_.getMessage();
        }
        return com.google.photos.types.proto.Video.getDefaultInstance();
      }
    }
    /**
     *
     *
     * <pre>
     * Metadata for a video media type.
     * </pre>
     *
     * <code>.google.photos.types.Video video = 7;</code>
     */
    public Builder setVideo(com.google.photos.types.proto.Video value) {
      if (videoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        videoBuilder_.setMessage(value);
      }
      metadataCase_ = 7;
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a video media type.
     * </pre>
     *
     * <code>.google.photos.types.Video video = 7;</code>
     */
    public Builder setVideo(com.google.photos.types.proto.Video.Builder builderForValue) {
      if (videoBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        videoBuilder_.setMessage(builderForValue.build());
      }
      metadataCase_ = 7;
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a video media type.
     * </pre>
     *
     * <code>.google.photos.types.Video video = 7;</code>
     */
    public Builder mergeVideo(com.google.photos.types.proto.Video value) {
      if (videoBuilder_ == null) {
        if (metadataCase_ == 7
            && metadata_ != com.google.photos.types.proto.Video.getDefaultInstance()) {
          metadata_ =
              com.google.photos.types.proto.Video.newBuilder(
                      (com.google.photos.types.proto.Video) metadata_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        if (metadataCase_ == 7) {
          videoBuilder_.mergeFrom(value);
        } else {
          videoBuilder_.setMessage(value);
        }
      }
      metadataCase_ = 7;
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a video media type.
     * </pre>
     *
     * <code>.google.photos.types.Video video = 7;</code>
     */
    public Builder clearVideo() {
      if (videoBuilder_ == null) {
        if (metadataCase_ == 7) {
          metadataCase_ = 0;
          metadata_ = null;
          onChanged();
        }
      } else {
        if (metadataCase_ == 7) {
          metadataCase_ = 0;
          metadata_ = null;
        }
        videoBuilder_.clear();
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata for a video media type.
     * </pre>
     *
     * <code>.google.photos.types.Video video = 7;</code>
     */
    public com.google.photos.types.proto.Video.Builder getVideoBuilder() {
      return getVideoFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Metadata for a video media type.
     * </pre>
     *
     * <code>.google.photos.types.Video video = 7;</code>
     */
    @java.lang.Override
    public com.google.photos.types.proto.VideoOrBuilder getVideoOrBuilder() {
      if ((metadataCase_ == 7) && (videoBuilder_ != null)) {
        return videoBuilder_.getMessageOrBuilder();
      } else {
        if (metadataCase_ == 7) {
          return (com.google.photos.types.proto.Video) metadata_;
        }
        return com.google.photos.types.proto.Video.getDefaultInstance();
      }
    }
    /**
     *
     *
     * <pre>
     * Metadata for a video media type.
     * </pre>
     *
     * <code>.google.photos.types.Video video = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.photos.types.proto.Video,
            com.google.photos.types.proto.Video.Builder,
            com.google.photos.types.proto.VideoOrBuilder>
        getVideoFieldBuilder() {
      if (videoBuilder_ == null) {
        if (!(metadataCase_ == 7)) {
          metadata_ = com.google.photos.types.proto.Video.getDefaultInstance();
        }
        videoBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.photos.types.proto.Video,
                com.google.photos.types.proto.Video.Builder,
                com.google.photos.types.proto.VideoOrBuilder>(
                (com.google.photos.types.proto.Video) metadata_, getParentForChildren(), isClean());
        metadata_ = null;
      }
      metadataCase_ = 7;
      onChanged();
      return videoBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.photos.types.MediaMetadata)
  }

  // @@protoc_insertion_point(class_scope:google.photos.types.MediaMetadata)
  private static final com.google.photos.types.proto.MediaMetadata DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.photos.types.proto.MediaMetadata();
  }

  public static com.google.photos.types.proto.MediaMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MediaMetadata> PARSER =
      new com.google.protobuf.AbstractParser<MediaMetadata>() {
        @java.lang.Override
        public MediaMetadata parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<MediaMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MediaMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.photos.types.proto.MediaMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
