// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/photos/types/media_item.proto

package com.google.photos.types.proto;

public final class MediaItemProto {
  private MediaItemProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_photos_types_MediaItem_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_photos_types_MediaItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_photos_types_MediaMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_photos_types_MediaMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_photos_types_Photo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_photos_types_Photo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_photos_types_Video_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_photos_types_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_photos_types_ContributorInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_photos_types_ContributorInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n$google/photos/types/media_item.proto\022\023"
          + "google.photos.types\032\036google/protobuf/dur"
          + "ation.proto\032\037google/protobuf/timestamp.p"
          + "roto\"\364\001\n\tMediaItem\022\n\n\002id\030\001 \001(\t\022\023\n\013descri"
          + "ption\030\002 \001(\t\022\023\n\013product_url\030\003 \001(\t\022\020\n\010base"
          + "_url\030\004 \001(\t\022\021\n\tmime_type\030\005 \001(\t\022:\n\016media_m"
          + "etadata\030\006 \001(\0132\".google.photos.types.Medi"
          + "aMetadata\022>\n\020contributor_info\030\007 \001(\0132$.go"
          + "ogle.photos.types.ContributorInfo\022\020\n\010fil"
          + "ename\030\010 \001(\t\"\307\001\n\rMediaMetadata\0221\n\rcreatio"
          + "n_time\030\001 \001(\0132\032.google.protobuf.Timestamp"
          + "\022\r\n\005width\030\002 \001(\003\022\016\n\006height\030\003 \001(\003\022+\n\005photo"
          + "\030\006 \001(\0132\032.google.photos.types.PhotoH\000\022+\n\005"
          + "video\030\007 \001(\0132\032.google.photos.types.VideoH"
          + "\000B\n\n\010metadata\"\255\001\n\005Photo\022\023\n\013camera_make\030\001"
          + " \001(\t\022\024\n\014camera_model\030\002 \001(\t\022\024\n\014focal_leng"
          + "th\030\003 \001(\002\022\031\n\021aperture_f_number\030\004 \001(\002\022\026\n\016i"
          + "so_equivalent\030\005 \001(\005\0220\n\rexposure_time\030\006 \001"
          + "(\0132\031.google.protobuf.Duration\"{\n\005Video\022\023"
          + "\n\013camera_make\030\001 \001(\t\022\024\n\014camera_model\030\002 \001("
          + "\t\022\013\n\003fps\030\003 \001(\001\022:\n\006status\030\004 \001(\0162*.google."
          + "photos.types.VideoProcessingStatus\"I\n\017Co"
          + "ntributorInfo\022 \n\030profile_picture_base_ur"
          + "l\030\001 \001(\t\022\024\n\014display_name\030\002 \001(\t*O\n\025VideoPr"
          + "ocessingStatus\022\017\n\013UNSPECIFIED\020\000\022\016\n\nPROCE"
          + "SSING\020\001\022\t\n\005READY\020\002\022\n\n\006FAILED\020\003Bk\n\035com.go"
          + "ogle.photos.types.protoB\016MediaItemProtoP"
          + "\001Z8google.golang.org/genproto/googleapis"
          + "/photos/types;typesb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.DurationProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_photos_types_MediaItem_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_photos_types_MediaItem_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_photos_types_MediaItem_descriptor,
            new java.lang.String[] {
              "Id",
              "Description",
              "ProductUrl",
              "BaseUrl",
              "MimeType",
              "MediaMetadata",
              "ContributorInfo",
              "Filename",
            });
    internal_static_google_photos_types_MediaMetadata_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_photos_types_MediaMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_photos_types_MediaMetadata_descriptor,
            new java.lang.String[] {
              "CreationTime", "Width", "Height", "Photo", "Video", "Metadata",
            });
    internal_static_google_photos_types_Photo_descriptor = getDescriptor().getMessageTypes().get(2);
    internal_static_google_photos_types_Photo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_photos_types_Photo_descriptor,
            new java.lang.String[] {
              "CameraMake",
              "CameraModel",
              "FocalLength",
              "ApertureFNumber",
              "IsoEquivalent",
              "ExposureTime",
            });
    internal_static_google_photos_types_Video_descriptor = getDescriptor().getMessageTypes().get(3);
    internal_static_google_photos_types_Video_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_photos_types_Video_descriptor,
            new java.lang.String[] {
              "CameraMake", "CameraModel", "Fps", "Status",
            });
    internal_static_google_photos_types_ContributorInfo_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_photos_types_ContributorInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_photos_types_ContributorInfo_descriptor,
            new java.lang.String[] {
              "ProfilePictureBaseUrl", "DisplayName",
            });
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
