// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/photos/types/media_item.proto

package com.google.photos.types.proto;

/**
 *
 *
 * <pre>
 * Representation of a media item (such as a photo or video) in Google Photos.
 * </pre>
 *
 * Protobuf type {@code google.photos.types.MediaItem}
 */
public final class MediaItem extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.photos.types.MediaItem)
    MediaItemOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use MediaItem.newBuilder() to construct.
  private MediaItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private MediaItem() {
    id_ = "";
    description_ = "";
    productUrl_ = "";
    baseUrl_ = "";
    mimeType_ = "";
    filename_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new MediaItem();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.photos.types.proto.MediaItemProto
        .internal_static_google_photos_types_MediaItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.photos.types.proto.MediaItemProto
        .internal_static_google_photos_types_MediaItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.photos.types.proto.MediaItem.class,
            com.google.photos.types.proto.MediaItem.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;

  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   *
   *
   * <pre>
   * Identifier for the media item. This is a persistent identifier that can be
   * used between sessions to identify this media item.
   * </pre>
   *
   * <code>string id = 1;</code>
   *
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Identifier for the media item. This is a persistent identifier that can be
   * used between sessions to identify this media item.
   * </pre>
   *
   * <code>string id = 1;</code>
   *
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;

  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   *
   *
   * <pre>
   * Description of the media item. This is shown to the user in the item's info
   * section in the Google Photos app. Must be shorter than 1000 characters.
   * Only include text written by users. Descriptions should add context and
   * help users understand media. Do not include any auto-generated
   * strings such as filenames, tags, and other metadata.
   * </pre>
   *
   * <code>string description = 2;</code>
   *
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Description of the media item. This is shown to the user in the item's info
   * section in the Google Photos app. Must be shorter than 1000 characters.
   * Only include text written by users. Descriptions should add context and
   * help users understand media. Do not include any auto-generated
   * strings such as filenames, tags, and other metadata.
   * </pre>
   *
   * <code>string description = 2;</code>
   *
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCT_URL_FIELD_NUMBER = 3;

  @SuppressWarnings("serial")
  private volatile java.lang.Object productUrl_ = "";
  /**
   *
   *
   * <pre>
   * Google Photos URL for the media item. This link is available to
   * the user only if they're signed in. When retrieved from an album search,
   * the URL points to the item inside the album.
   * </pre>
   *
   * <code>string product_url = 3;</code>
   *
   * @return The productUrl.
   */
  @java.lang.Override
  public java.lang.String getProductUrl() {
    java.lang.Object ref = productUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productUrl_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Google Photos URL for the media item. This link is available to
   * the user only if they're signed in. When retrieved from an album search,
   * the URL points to the item inside the album.
   * </pre>
   *
   * <code>string product_url = 3;</code>
   *
   * @return The bytes for productUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getProductUrlBytes() {
    java.lang.Object ref = productUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      productUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BASE_URL_FIELD_NUMBER = 4;

  @SuppressWarnings("serial")
  private volatile java.lang.Object baseUrl_ = "";
  /**
   *
   *
   * <pre>
   * A URL to the media item's bytes. This shouldn't be used as is. Parameters
   * should be appended to this URL before use. See the [developer
   * documentation](https://developers.google.com/photos/library/guides/access-media-items#base-urls)
   * for a complete list of supported parameters. For example, `'=w2048-h1024'`
   * will set the dimensions of a media item of type photo to have a width of
   * 2048 px and height of 1024 px.
   * </pre>
   *
   * <code>string base_url = 4;</code>
   *
   * @return The baseUrl.
   */
  @java.lang.Override
  public java.lang.String getBaseUrl() {
    java.lang.Object ref = baseUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      baseUrl_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * A URL to the media item's bytes. This shouldn't be used as is. Parameters
   * should be appended to this URL before use. See the [developer
   * documentation](https://developers.google.com/photos/library/guides/access-media-items#base-urls)
   * for a complete list of supported parameters. For example, `'=w2048-h1024'`
   * will set the dimensions of a media item of type photo to have a width of
   * 2048 px and height of 1024 px.
   * </pre>
   *
   * <code>string base_url = 4;</code>
   *
   * @return The bytes for baseUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBaseUrlBytes() {
    java.lang.Object ref = baseUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      baseUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MIME_TYPE_FIELD_NUMBER = 5;

  @SuppressWarnings("serial")
  private volatile java.lang.Object mimeType_ = "";
  /**
   *
   *
   * <pre>
   * MIME type of the media item. For example, `image/jpeg`.
   * </pre>
   *
   * <code>string mime_type = 5;</code>
   *
   * @return The mimeType.
   */
  @java.lang.Override
  public java.lang.String getMimeType() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mimeType_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * MIME type of the media item. For example, `image/jpeg`.
   * </pre>
   *
   * <code>string mime_type = 5;</code>
   *
   * @return The bytes for mimeType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMimeTypeBytes() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      mimeType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIA_METADATA_FIELD_NUMBER = 6;
  private com.google.photos.types.proto.MediaMetadata mediaMetadata_;
  /**
   *
   *
   * <pre>
   * Metadata related to the media item, such as, height, width, or
   * creation time.
   * </pre>
   *
   * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
   *
   * @return Whether the mediaMetadata field is set.
   */
  @java.lang.Override
  public boolean hasMediaMetadata() {
    return mediaMetadata_ != null;
  }
  /**
   *
   *
   * <pre>
   * Metadata related to the media item, such as, height, width, or
   * creation time.
   * </pre>
   *
   * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
   *
   * @return The mediaMetadata.
   */
  @java.lang.Override
  public com.google.photos.types.proto.MediaMetadata getMediaMetadata() {
    return mediaMetadata_ == null
        ? com.google.photos.types.proto.MediaMetadata.getDefaultInstance()
        : mediaMetadata_;
  }
  /**
   *
   *
   * <pre>
   * Metadata related to the media item, such as, height, width, or
   * creation time.
   * </pre>
   *
   * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
   */
  @java.lang.Override
  public com.google.photos.types.proto.MediaMetadataOrBuilder getMediaMetadataOrBuilder() {
    return mediaMetadata_ == null
        ? com.google.photos.types.proto.MediaMetadata.getDefaultInstance()
        : mediaMetadata_;
  }

  public static final int CONTRIBUTOR_INFO_FIELD_NUMBER = 7;
  private com.google.photos.types.proto.ContributorInfo contributorInfo_;
  /**
   *
   *
   * <pre>
   * Information about the user who added this media item. Note that this
   * is only included when using [mediaItems.search]
   * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
   * ID of a shared album. The album must be created by your app and
   * you must have the sharing scope.
   * </pre>
   *
   * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
   *
   * @return Whether the contributorInfo field is set.
   */
  @java.lang.Override
  public boolean hasContributorInfo() {
    return contributorInfo_ != null;
  }
  /**
   *
   *
   * <pre>
   * Information about the user who added this media item. Note that this
   * is only included when using [mediaItems.search]
   * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
   * ID of a shared album. The album must be created by your app and
   * you must have the sharing scope.
   * </pre>
   *
   * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
   *
   * @return The contributorInfo.
   */
  @java.lang.Override
  public com.google.photos.types.proto.ContributorInfo getContributorInfo() {
    return contributorInfo_ == null
        ? com.google.photos.types.proto.ContributorInfo.getDefaultInstance()
        : contributorInfo_;
  }
  /**
   *
   *
   * <pre>
   * Information about the user who added this media item. Note that this
   * is only included when using [mediaItems.search]
   * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
   * ID of a shared album. The album must be created by your app and
   * you must have the sharing scope.
   * </pre>
   *
   * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
   */
  @java.lang.Override
  public com.google.photos.types.proto.ContributorInfoOrBuilder getContributorInfoOrBuilder() {
    return contributorInfo_ == null
        ? com.google.photos.types.proto.ContributorInfo.getDefaultInstance()
        : contributorInfo_;
  }

  public static final int FILENAME_FIELD_NUMBER = 8;

  @SuppressWarnings("serial")
  private volatile java.lang.Object filename_ = "";
  /**
   *
   *
   * <pre>
   * Filename of the media item. This is shown to the user in the item's info
   * section in the Google Photos app.
   * </pre>
   *
   * <code>string filename = 8;</code>
   *
   * @return The filename.
   */
  @java.lang.Override
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Filename of the media item. This is shown to the user in the item's info
   * section in the Google Photos app.
   * </pre>
   *
   * <code>string filename = 8;</code>
   *
   * @return The bytes for filename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, baseUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mimeType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mimeType_);
    }
    if (mediaMetadata_ != null) {
      output.writeMessage(6, getMediaMetadata());
    }
    if (contributorInfo_ != null) {
      output.writeMessage(7, getContributorInfo());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filename_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, filename_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, baseUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mimeType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mimeType_);
    }
    if (mediaMetadata_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(6, getMediaMetadata());
    }
    if (contributorInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(7, getContributorInfo());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filename_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, filename_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.photos.types.proto.MediaItem)) {
      return super.equals(obj);
    }
    com.google.photos.types.proto.MediaItem other = (com.google.photos.types.proto.MediaItem) obj;

    if (!getId().equals(other.getId())) return false;
    if (!getDescription().equals(other.getDescription())) return false;
    if (!getProductUrl().equals(other.getProductUrl())) return false;
    if (!getBaseUrl().equals(other.getBaseUrl())) return false;
    if (!getMimeType().equals(other.getMimeType())) return false;
    if (hasMediaMetadata() != other.hasMediaMetadata()) return false;
    if (hasMediaMetadata()) {
      if (!getMediaMetadata().equals(other.getMediaMetadata())) return false;
    }
    if (hasContributorInfo() != other.hasContributorInfo()) return false;
    if (hasContributorInfo()) {
      if (!getContributorInfo().equals(other.getContributorInfo())) return false;
    }
    if (!getFilename().equals(other.getFilename())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + PRODUCT_URL_FIELD_NUMBER;
    hash = (53 * hash) + getProductUrl().hashCode();
    hash = (37 * hash) + BASE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getBaseUrl().hashCode();
    hash = (37 * hash) + MIME_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMimeType().hashCode();
    if (hasMediaMetadata()) {
      hash = (37 * hash) + MEDIA_METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMediaMetadata().hashCode();
    }
    if (hasContributorInfo()) {
      hash = (37 * hash) + CONTRIBUTOR_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getContributorInfo().hashCode();
    }
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaItem parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.photos.types.proto.MediaItem parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.photos.types.proto.MediaItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.photos.types.proto.MediaItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Representation of a media item (such as a photo or video) in Google Photos.
   * </pre>
   *
   * Protobuf type {@code google.photos.types.MediaItem}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.photos.types.MediaItem)
      com.google.photos.types.proto.MediaItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.photos.types.proto.MediaItemProto
          .internal_static_google_photos_types_MediaItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.photos.types.proto.MediaItemProto
          .internal_static_google_photos_types_MediaItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.photos.types.proto.MediaItem.class,
              com.google.photos.types.proto.MediaItem.Builder.class);
    }

    // Construct using com.google.photos.types.proto.MediaItem.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      description_ = "";
      productUrl_ = "";
      baseUrl_ = "";
      mimeType_ = "";
      mediaMetadata_ = null;
      if (mediaMetadataBuilder_ != null) {
        mediaMetadataBuilder_.dispose();
        mediaMetadataBuilder_ = null;
      }
      contributorInfo_ = null;
      if (contributorInfoBuilder_ != null) {
        contributorInfoBuilder_.dispose();
        contributorInfoBuilder_ = null;
      }
      filename_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.photos.types.proto.MediaItemProto
          .internal_static_google_photos_types_MediaItem_descriptor;
    }

    @java.lang.Override
    public com.google.photos.types.proto.MediaItem getDefaultInstanceForType() {
      return com.google.photos.types.proto.MediaItem.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.photos.types.proto.MediaItem build() {
      com.google.photos.types.proto.MediaItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.photos.types.proto.MediaItem buildPartial() {
      com.google.photos.types.proto.MediaItem result =
          new com.google.photos.types.proto.MediaItem(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.photos.types.proto.MediaItem result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.productUrl_ = productUrl_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.baseUrl_ = baseUrl_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.mimeType_ = mimeType_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.mediaMetadata_ =
            mediaMetadataBuilder_ == null ? mediaMetadata_ : mediaMetadataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.contributorInfo_ =
            contributorInfoBuilder_ == null ? contributorInfo_ : contributorInfoBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.filename_ = filename_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.photos.types.proto.MediaItem) {
        return mergeFrom((com.google.photos.types.proto.MediaItem) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.photos.types.proto.MediaItem other) {
      if (other == com.google.photos.types.proto.MediaItem.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getProductUrl().isEmpty()) {
        productUrl_ = other.productUrl_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getBaseUrl().isEmpty()) {
        baseUrl_ = other.baseUrl_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getMimeType().isEmpty()) {
        mimeType_ = other.mimeType_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasMediaMetadata()) {
        mergeMediaMetadata(other.getMediaMetadata());
      }
      if (other.hasContributorInfo()) {
        mergeContributorInfo(other.getContributorInfo());
      }
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 18:
              {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
            case 26:
              {
                productUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
            case 34:
              {
                baseUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
            case 42:
              {
                mimeType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
            case 50:
              {
                input.readMessage(getMediaMetadataFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
            case 58:
              {
                input.readMessage(getContributorInfoFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
            case 66:
              {
                filename_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     *
     *
     * <pre>
     * Identifier for the media item. This is a persistent identifier that can be
     * used between sessions to identify this media item.
     * </pre>
     *
     * <code>string id = 1;</code>
     *
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Identifier for the media item. This is a persistent identifier that can be
     * used between sessions to identify this media item.
     * </pre>
     *
     * <code>string id = 1;</code>
     *
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Identifier for the media item. This is a persistent identifier that can be
     * used between sessions to identify this media item.
     * </pre>
     *
     * <code>string id = 1;</code>
     *
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Identifier for the media item. This is a persistent identifier that can be
     * used between sessions to identify this media item.
     * </pre>
     *
     * <code>string id = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Identifier for the media item. This is a persistent identifier that can be
     * used between sessions to identify this media item.
     * </pre>
     *
     * <code>string id = 1;</code>
     *
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     *
     *
     * <pre>
     * Description of the media item. This is shown to the user in the item's info
     * section in the Google Photos app. Must be shorter than 1000 characters.
     * Only include text written by users. Descriptions should add context and
     * help users understand media. Do not include any auto-generated
     * strings such as filenames, tags, and other metadata.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Description of the media item. This is shown to the user in the item's info
     * section in the Google Photos app. Must be shorter than 1000 characters.
     * Only include text written by users. Descriptions should add context and
     * help users understand media. Do not include any auto-generated
     * strings such as filenames, tags, and other metadata.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Description of the media item. This is shown to the user in the item's info
     * section in the Google Photos app. Must be shorter than 1000 characters.
     * Only include text written by users. Descriptions should add context and
     * help users understand media. Do not include any auto-generated
     * strings such as filenames, tags, and other metadata.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Description of the media item. This is shown to the user in the item's info
     * section in the Google Photos app. Must be shorter than 1000 characters.
     * Only include text written by users. Descriptions should add context and
     * help users understand media. Do not include any auto-generated
     * strings such as filenames, tags, and other metadata.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Description of the media item. This is shown to the user in the item's info
     * section in the Google Photos app. Must be shorter than 1000 characters.
     * Only include text written by users. Descriptions should add context and
     * help users understand media. Do not include any auto-generated
     * strings such as filenames, tags, and other metadata.
     * </pre>
     *
     * <code>string description = 2;</code>
     *
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object productUrl_ = "";
    /**
     *
     *
     * <pre>
     * Google Photos URL for the media item. This link is available to
     * the user only if they're signed in. When retrieved from an album search,
     * the URL points to the item inside the album.
     * </pre>
     *
     * <code>string product_url = 3;</code>
     *
     * @return The productUrl.
     */
    public java.lang.String getProductUrl() {
      java.lang.Object ref = productUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Google Photos URL for the media item. This link is available to
     * the user only if they're signed in. When retrieved from an album search,
     * the URL points to the item inside the album.
     * </pre>
     *
     * <code>string product_url = 3;</code>
     *
     * @return The bytes for productUrl.
     */
    public com.google.protobuf.ByteString getProductUrlBytes() {
      java.lang.Object ref = productUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        productUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Google Photos URL for the media item. This link is available to
     * the user only if they're signed in. When retrieved from an album search,
     * the URL points to the item inside the album.
     * </pre>
     *
     * <code>string product_url = 3;</code>
     *
     * @param value The productUrl to set.
     * @return This builder for chaining.
     */
    public Builder setProductUrl(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      productUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Google Photos URL for the media item. This link is available to
     * the user only if they're signed in. When retrieved from an album search,
     * the URL points to the item inside the album.
     * </pre>
     *
     * <code>string product_url = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearProductUrl() {
      productUrl_ = getDefaultInstance().getProductUrl();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Google Photos URL for the media item. This link is available to
     * the user only if they're signed in. When retrieved from an album search,
     * the URL points to the item inside the album.
     * </pre>
     *
     * <code>string product_url = 3;</code>
     *
     * @param value The bytes for productUrl to set.
     * @return This builder for chaining.
     */
    public Builder setProductUrlBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      productUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object baseUrl_ = "";
    /**
     *
     *
     * <pre>
     * A URL to the media item's bytes. This shouldn't be used as is. Parameters
     * should be appended to this URL before use. See the [developer
     * documentation](https://developers.google.com/photos/library/guides/access-media-items#base-urls)
     * for a complete list of supported parameters. For example, `'=w2048-h1024'`
     * will set the dimensions of a media item of type photo to have a width of
     * 2048 px and height of 1024 px.
     * </pre>
     *
     * <code>string base_url = 4;</code>
     *
     * @return The baseUrl.
     */
    public java.lang.String getBaseUrl() {
      java.lang.Object ref = baseUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * A URL to the media item's bytes. This shouldn't be used as is. Parameters
     * should be appended to this URL before use. See the [developer
     * documentation](https://developers.google.com/photos/library/guides/access-media-items#base-urls)
     * for a complete list of supported parameters. For example, `'=w2048-h1024'`
     * will set the dimensions of a media item of type photo to have a width of
     * 2048 px and height of 1024 px.
     * </pre>
     *
     * <code>string base_url = 4;</code>
     *
     * @return The bytes for baseUrl.
     */
    public com.google.protobuf.ByteString getBaseUrlBytes() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        baseUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * A URL to the media item's bytes. This shouldn't be used as is. Parameters
     * should be appended to this URL before use. See the [developer
     * documentation](https://developers.google.com/photos/library/guides/access-media-items#base-urls)
     * for a complete list of supported parameters. For example, `'=w2048-h1024'`
     * will set the dimensions of a media item of type photo to have a width of
     * 2048 px and height of 1024 px.
     * </pre>
     *
     * <code>string base_url = 4;</code>
     *
     * @param value The baseUrl to set.
     * @return This builder for chaining.
     */
    public Builder setBaseUrl(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      baseUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A URL to the media item's bytes. This shouldn't be used as is. Parameters
     * should be appended to this URL before use. See the [developer
     * documentation](https://developers.google.com/photos/library/guides/access-media-items#base-urls)
     * for a complete list of supported parameters. For example, `'=w2048-h1024'`
     * will set the dimensions of a media item of type photo to have a width of
     * 2048 px and height of 1024 px.
     * </pre>
     *
     * <code>string base_url = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearBaseUrl() {
      baseUrl_ = getDefaultInstance().getBaseUrl();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A URL to the media item's bytes. This shouldn't be used as is. Parameters
     * should be appended to this URL before use. See the [developer
     * documentation](https://developers.google.com/photos/library/guides/access-media-items#base-urls)
     * for a complete list of supported parameters. For example, `'=w2048-h1024'`
     * will set the dimensions of a media item of type photo to have a width of
     * 2048 px and height of 1024 px.
     * </pre>
     *
     * <code>string base_url = 4;</code>
     *
     * @param value The bytes for baseUrl to set.
     * @return This builder for chaining.
     */
    public Builder setBaseUrlBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      baseUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object mimeType_ = "";
    /**
     *
     *
     * <pre>
     * MIME type of the media item. For example, `image/jpeg`.
     * </pre>
     *
     * <code>string mime_type = 5;</code>
     *
     * @return The mimeType.
     */
    public java.lang.String getMimeType() {
      java.lang.Object ref = mimeType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mimeType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * MIME type of the media item. For example, `image/jpeg`.
     * </pre>
     *
     * <code>string mime_type = 5;</code>
     *
     * @return The bytes for mimeType.
     */
    public com.google.protobuf.ByteString getMimeTypeBytes() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * MIME type of the media item. For example, `image/jpeg`.
     * </pre>
     *
     * <code>string mime_type = 5;</code>
     *
     * @param value The mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeType(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      mimeType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * MIME type of the media item. For example, `image/jpeg`.
     * </pre>
     *
     * <code>string mime_type = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearMimeType() {
      mimeType_ = getDefaultInstance().getMimeType();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * MIME type of the media item. For example, `image/jpeg`.
     * </pre>
     *
     * <code>string mime_type = 5;</code>
     *
     * @param value The bytes for mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeTypeBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      mimeType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.photos.types.proto.MediaMetadata mediaMetadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.photos.types.proto.MediaMetadata,
            com.google.photos.types.proto.MediaMetadata.Builder,
            com.google.photos.types.proto.MediaMetadataOrBuilder>
        mediaMetadataBuilder_;
    /**
     *
     *
     * <pre>
     * Metadata related to the media item, such as, height, width, or
     * creation time.
     * </pre>
     *
     * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
     *
     * @return Whether the mediaMetadata field is set.
     */
    public boolean hasMediaMetadata() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     *
     *
     * <pre>
     * Metadata related to the media item, such as, height, width, or
     * creation time.
     * </pre>
     *
     * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
     *
     * @return The mediaMetadata.
     */
    public com.google.photos.types.proto.MediaMetadata getMediaMetadata() {
      if (mediaMetadataBuilder_ == null) {
        return mediaMetadata_ == null
            ? com.google.photos.types.proto.MediaMetadata.getDefaultInstance()
            : mediaMetadata_;
      } else {
        return mediaMetadataBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Metadata related to the media item, such as, height, width, or
     * creation time.
     * </pre>
     *
     * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
     */
    public Builder setMediaMetadata(com.google.photos.types.proto.MediaMetadata value) {
      if (mediaMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mediaMetadata_ = value;
      } else {
        mediaMetadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata related to the media item, such as, height, width, or
     * creation time.
     * </pre>
     *
     * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
     */
    public Builder setMediaMetadata(
        com.google.photos.types.proto.MediaMetadata.Builder builderForValue) {
      if (mediaMetadataBuilder_ == null) {
        mediaMetadata_ = builderForValue.build();
      } else {
        mediaMetadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata related to the media item, such as, height, width, or
     * creation time.
     * </pre>
     *
     * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
     */
    public Builder mergeMediaMetadata(com.google.photos.types.proto.MediaMetadata value) {
      if (mediaMetadataBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)
            && mediaMetadata_ != null
            && mediaMetadata_ != com.google.photos.types.proto.MediaMetadata.getDefaultInstance()) {
          getMediaMetadataBuilder().mergeFrom(value);
        } else {
          mediaMetadata_ = value;
        }
      } else {
        mediaMetadataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata related to the media item, such as, height, width, or
     * creation time.
     * </pre>
     *
     * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
     */
    public Builder clearMediaMetadata() {
      bitField0_ = (bitField0_ & ~0x00000020);
      mediaMetadata_ = null;
      if (mediaMetadataBuilder_ != null) {
        mediaMetadataBuilder_.dispose();
        mediaMetadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Metadata related to the media item, such as, height, width, or
     * creation time.
     * </pre>
     *
     * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
     */
    public com.google.photos.types.proto.MediaMetadata.Builder getMediaMetadataBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getMediaMetadataFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Metadata related to the media item, such as, height, width, or
     * creation time.
     * </pre>
     *
     * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
     */
    public com.google.photos.types.proto.MediaMetadataOrBuilder getMediaMetadataOrBuilder() {
      if (mediaMetadataBuilder_ != null) {
        return mediaMetadataBuilder_.getMessageOrBuilder();
      } else {
        return mediaMetadata_ == null
            ? com.google.photos.types.proto.MediaMetadata.getDefaultInstance()
            : mediaMetadata_;
      }
    }
    /**
     *
     *
     * <pre>
     * Metadata related to the media item, such as, height, width, or
     * creation time.
     * </pre>
     *
     * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.photos.types.proto.MediaMetadata,
            com.google.photos.types.proto.MediaMetadata.Builder,
            com.google.photos.types.proto.MediaMetadataOrBuilder>
        getMediaMetadataFieldBuilder() {
      if (mediaMetadataBuilder_ == null) {
        mediaMetadataBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.photos.types.proto.MediaMetadata,
                com.google.photos.types.proto.MediaMetadata.Builder,
                com.google.photos.types.proto.MediaMetadataOrBuilder>(
                getMediaMetadata(), getParentForChildren(), isClean());
        mediaMetadata_ = null;
      }
      return mediaMetadataBuilder_;
    }

    private com.google.photos.types.proto.ContributorInfo contributorInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.photos.types.proto.ContributorInfo,
            com.google.photos.types.proto.ContributorInfo.Builder,
            com.google.photos.types.proto.ContributorInfoOrBuilder>
        contributorInfoBuilder_;
    /**
     *
     *
     * <pre>
     * Information about the user who added this media item. Note that this
     * is only included when using [mediaItems.search]
     * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
     * ID of a shared album. The album must be created by your app and
     * you must have the sharing scope.
     * </pre>
     *
     * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
     *
     * @return Whether the contributorInfo field is set.
     */
    public boolean hasContributorInfo() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     *
     *
     * <pre>
     * Information about the user who added this media item. Note that this
     * is only included when using [mediaItems.search]
     * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
     * ID of a shared album. The album must be created by your app and
     * you must have the sharing scope.
     * </pre>
     *
     * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
     *
     * @return The contributorInfo.
     */
    public com.google.photos.types.proto.ContributorInfo getContributorInfo() {
      if (contributorInfoBuilder_ == null) {
        return contributorInfo_ == null
            ? com.google.photos.types.proto.ContributorInfo.getDefaultInstance()
            : contributorInfo_;
      } else {
        return contributorInfoBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Information about the user who added this media item. Note that this
     * is only included when using [mediaItems.search]
     * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
     * ID of a shared album. The album must be created by your app and
     * you must have the sharing scope.
     * </pre>
     *
     * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
     */
    public Builder setContributorInfo(com.google.photos.types.proto.ContributorInfo value) {
      if (contributorInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contributorInfo_ = value;
      } else {
        contributorInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Information about the user who added this media item. Note that this
     * is only included when using [mediaItems.search]
     * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
     * ID of a shared album. The album must be created by your app and
     * you must have the sharing scope.
     * </pre>
     *
     * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
     */
    public Builder setContributorInfo(
        com.google.photos.types.proto.ContributorInfo.Builder builderForValue) {
      if (contributorInfoBuilder_ == null) {
        contributorInfo_ = builderForValue.build();
      } else {
        contributorInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Information about the user who added this media item. Note that this
     * is only included when using [mediaItems.search]
     * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
     * ID of a shared album. The album must be created by your app and
     * you must have the sharing scope.
     * </pre>
     *
     * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
     */
    public Builder mergeContributorInfo(com.google.photos.types.proto.ContributorInfo value) {
      if (contributorInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)
            && contributorInfo_ != null
            && contributorInfo_
                != com.google.photos.types.proto.ContributorInfo.getDefaultInstance()) {
          getContributorInfoBuilder().mergeFrom(value);
        } else {
          contributorInfo_ = value;
        }
      } else {
        contributorInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Information about the user who added this media item. Note that this
     * is only included when using [mediaItems.search]
     * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
     * ID of a shared album. The album must be created by your app and
     * you must have the sharing scope.
     * </pre>
     *
     * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
     */
    public Builder clearContributorInfo() {
      bitField0_ = (bitField0_ & ~0x00000040);
      contributorInfo_ = null;
      if (contributorInfoBuilder_ != null) {
        contributorInfoBuilder_.dispose();
        contributorInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Information about the user who added this media item. Note that this
     * is only included when using [mediaItems.search]
     * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
     * ID of a shared album. The album must be created by your app and
     * you must have the sharing scope.
     * </pre>
     *
     * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
     */
    public com.google.photos.types.proto.ContributorInfo.Builder getContributorInfoBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getContributorInfoFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Information about the user who added this media item. Note that this
     * is only included when using [mediaItems.search]
     * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
     * ID of a shared album. The album must be created by your app and
     * you must have the sharing scope.
     * </pre>
     *
     * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
     */
    public com.google.photos.types.proto.ContributorInfoOrBuilder getContributorInfoOrBuilder() {
      if (contributorInfoBuilder_ != null) {
        return contributorInfoBuilder_.getMessageOrBuilder();
      } else {
        return contributorInfo_ == null
            ? com.google.photos.types.proto.ContributorInfo.getDefaultInstance()
            : contributorInfo_;
      }
    }
    /**
     *
     *
     * <pre>
     * Information about the user who added this media item. Note that this
     * is only included when using [mediaItems.search]
     * [google.photos.library.v1.PhotosLibrary.SearchMediaItems] with the
     * ID of a shared album. The album must be created by your app and
     * you must have the sharing scope.
     * </pre>
     *
     * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.photos.types.proto.ContributorInfo,
            com.google.photos.types.proto.ContributorInfo.Builder,
            com.google.photos.types.proto.ContributorInfoOrBuilder>
        getContributorInfoFieldBuilder() {
      if (contributorInfoBuilder_ == null) {
        contributorInfoBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.photos.types.proto.ContributorInfo,
                com.google.photos.types.proto.ContributorInfo.Builder,
                com.google.photos.types.proto.ContributorInfoOrBuilder>(
                getContributorInfo(), getParentForChildren(), isClean());
        contributorInfo_ = null;
      }
      return contributorInfoBuilder_;
    }

    private java.lang.Object filename_ = "";
    /**
     *
     *
     * <pre>
     * Filename of the media item. This is shown to the user in the item's info
     * section in the Google Photos app.
     * </pre>
     *
     * <code>string filename = 8;</code>
     *
     * @return The filename.
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Filename of the media item. This is shown to the user in the item's info
     * section in the Google Photos app.
     * </pre>
     *
     * <code>string filename = 8;</code>
     *
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Filename of the media item. This is shown to the user in the item's info
     * section in the Google Photos app.
     * </pre>
     *
     * <code>string filename = 8;</code>
     *
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      filename_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Filename of the media item. This is shown to the user in the item's info
     * section in the Google Photos app.
     * </pre>
     *
     * <code>string filename = 8;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      filename_ = getDefaultInstance().getFilename();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Filename of the media item. This is shown to the user in the item's info
     * section in the Google Photos app.
     * </pre>
     *
     * <code>string filename = 8;</code>
     *
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      filename_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.photos.types.MediaItem)
  }

  // @@protoc_insertion_point(class_scope:google.photos.types.MediaItem)
  private static final com.google.photos.types.proto.MediaItem DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.photos.types.proto.MediaItem();
  }

  public static com.google.photos.types.proto.MediaItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MediaItem> PARSER =
      new com.google.protobuf.AbstractParser<MediaItem>() {
        @java.lang.Override
        public MediaItem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<MediaItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MediaItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.photos.types.proto.MediaItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
