// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/photos/types/media_item.proto

package com.google.photos.types.proto;

public interface MediaItemOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.photos.types.MediaItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Identifier for the media item. This is a persistent identifier that can be
   * used between sessions to identify this media item.
   * </pre>
   *
   * <code>string id = 1;</code>
   *
   * @return The id.
   */
  java.lang.String getId();
  /**
   *
   *
   * <pre>
   * Identifier for the media item. This is a persistent identifier that can be
   * used between sessions to identify this media item.
   * </pre>
   *
   * <code>string id = 1;</code>
   *
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString getIdBytes();

  /**
   *
   *
   * <pre>
   * Description of the media item. This is shown to the user in the item's
   * info section in the Google Photos app.
   * </pre>
   *
   * <code>string description = 2;</code>
   *
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   *
   *
   * <pre>
   * Description of the media item. This is shown to the user in the item's
   * info section in the Google Photos app.
   * </pre>
   *
   * <code>string description = 2;</code>
   *
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString getDescriptionBytes();

  /**
   *
   *
   * <pre>
   * Google Photos URL for the media item. This link is available to
   * the user only if they're signed in.
   * </pre>
   *
   * <code>string product_url = 3;</code>
   *
   * @return The productUrl.
   */
  java.lang.String getProductUrl();
  /**
   *
   *
   * <pre>
   * Google Photos URL for the media item. This link is available to
   * the user only if they're signed in.
   * </pre>
   *
   * <code>string product_url = 3;</code>
   *
   * @return The bytes for productUrl.
   */
  com.google.protobuf.ByteString getProductUrlBytes();

  /**
   *
   *
   * <pre>
   * A URL to the media item's bytes. This shouldn't be used as is. Parameters
   * should be appended to this URL before use. See the [developer
   * documentation](https://developers.google.com/photos/library/guides/access-media-items#base-urls)
   * for a complete list of supported parameters. For example, `'=w2048-h1024'`
   * will set the dimensions of a media item of type photo to have a width of
   * 2048 px and height of 1024 px.
   * </pre>
   *
   * <code>string base_url = 4;</code>
   *
   * @return The baseUrl.
   */
  java.lang.String getBaseUrl();
  /**
   *
   *
   * <pre>
   * A URL to the media item's bytes. This shouldn't be used as is. Parameters
   * should be appended to this URL before use. See the [developer
   * documentation](https://developers.google.com/photos/library/guides/access-media-items#base-urls)
   * for a complete list of supported parameters. For example, `'=w2048-h1024'`
   * will set the dimensions of a media item of type photo to have a width of
   * 2048 px and height of 1024 px.
   * </pre>
   *
   * <code>string base_url = 4;</code>
   *
   * @return The bytes for baseUrl.
   */
  com.google.protobuf.ByteString getBaseUrlBytes();

  /**
   *
   *
   * <pre>
   * MIME type of the media item. For example, `image/jpeg`.
   * </pre>
   *
   * <code>string mime_type = 5;</code>
   *
   * @return The mimeType.
   */
  java.lang.String getMimeType();
  /**
   *
   *
   * <pre>
   * MIME type of the media item. For example, `image/jpeg`.
   * </pre>
   *
   * <code>string mime_type = 5;</code>
   *
   * @return The bytes for mimeType.
   */
  com.google.protobuf.ByteString getMimeTypeBytes();

  /**
   *
   *
   * <pre>
   * Metadata related to the media item, such as, height, width, or
   * creation time.
   * </pre>
   *
   * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
   *
   * @return Whether the mediaMetadata field is set.
   */
  boolean hasMediaMetadata();
  /**
   *
   *
   * <pre>
   * Metadata related to the media item, such as, height, width, or
   * creation time.
   * </pre>
   *
   * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
   *
   * @return The mediaMetadata.
   */
  com.google.photos.types.proto.MediaMetadata getMediaMetadata();
  /**
   *
   *
   * <pre>
   * Metadata related to the media item, such as, height, width, or
   * creation time.
   * </pre>
   *
   * <code>.google.photos.types.MediaMetadata media_metadata = 6;</code>
   */
  com.google.photos.types.proto.MediaMetadataOrBuilder getMediaMetadataOrBuilder();

  /**
   *
   *
   * <pre>
   * Information about the user who created this media item.
   * </pre>
   *
   * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
   *
   * @return Whether the contributorInfo field is set.
   */
  boolean hasContributorInfo();
  /**
   *
   *
   * <pre>
   * Information about the user who created this media item.
   * </pre>
   *
   * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
   *
   * @return The contributorInfo.
   */
  com.google.photos.types.proto.ContributorInfo getContributorInfo();
  /**
   *
   *
   * <pre>
   * Information about the user who created this media item.
   * </pre>
   *
   * <code>.google.photos.types.ContributorInfo contributor_info = 7;</code>
   */
  com.google.photos.types.proto.ContributorInfoOrBuilder getContributorInfoOrBuilder();

  /**
   *
   *
   * <pre>
   * Filename of the media item. This is shown to the user in the item's info
   * section in the Google Photos app.
   * </pre>
   *
   * <code>string filename = 8;</code>
   *
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   *
   *
   * <pre>
   * Filename of the media item. This is shown to the user in the item's info
   * section in the Google Photos app.
   * </pre>
   *
   * <code>string filename = 8;</code>
   *
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString getFilenameBytes();
}
