// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/photos/types/media_item.proto

package com.google.photos.types.proto;

public interface MediaMetadataOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.photos.types.MediaMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Time when the media item was first created (not when it was uploaded to
   * Google Photos).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp creation_time = 1;</code>
   *
   * @return Whether the creationTime field is set.
   */
  boolean hasCreationTime();
  /**
   *
   *
   * <pre>
   * Time when the media item was first created (not when it was uploaded to
   * Google Photos).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp creation_time = 1;</code>
   *
   * @return The creationTime.
   */
  com.google.protobuf.Timestamp getCreationTime();
  /**
   *
   *
   * <pre>
   * Time when the media item was first created (not when it was uploaded to
   * Google Photos).
   * </pre>
   *
   * <code>.google.protobuf.Timestamp creation_time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreationTimeOrBuilder();

  /**
   *
   *
   * <pre>
   * Original width (in pixels) of the media item.
   * </pre>
   *
   * <code>int64 width = 2;</code>
   *
   * @return The width.
   */
  long getWidth();

  /**
   *
   *
   * <pre>
   * Original height (in pixels) of the media item.
   * </pre>
   *
   * <code>int64 height = 3;</code>
   *
   * @return The height.
   */
  long getHeight();

  /**
   *
   *
   * <pre>
   * Metadata for a photo media type.
   * </pre>
   *
   * <code>.google.photos.types.Photo photo = 6;</code>
   *
   * @return Whether the photo field is set.
   */
  boolean hasPhoto();
  /**
   *
   *
   * <pre>
   * Metadata for a photo media type.
   * </pre>
   *
   * <code>.google.photos.types.Photo photo = 6;</code>
   *
   * @return The photo.
   */
  com.google.photos.types.proto.Photo getPhoto();
  /**
   *
   *
   * <pre>
   * Metadata for a photo media type.
   * </pre>
   *
   * <code>.google.photos.types.Photo photo = 6;</code>
   */
  com.google.photos.types.proto.PhotoOrBuilder getPhotoOrBuilder();

  /**
   *
   *
   * <pre>
   * Metadata for a video media type.
   * </pre>
   *
   * <code>.google.photos.types.Video video = 7;</code>
   *
   * @return Whether the video field is set.
   */
  boolean hasVideo();
  /**
   *
   *
   * <pre>
   * Metadata for a video media type.
   * </pre>
   *
   * <code>.google.photos.types.Video video = 7;</code>
   *
   * @return The video.
   */
  com.google.photos.types.proto.Video getVideo();
  /**
   *
   *
   * <pre>
   * Metadata for a video media type.
   * </pre>
   *
   * <code>.google.photos.types.Video video = 7;</code>
   */
  com.google.photos.types.proto.VideoOrBuilder getVideoOrBuilder();

  public com.google.photos.types.proto.MediaMetadata.MetadataCase getMetadataCase();
}
