// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/photos/types/album.proto

package com.google.photos.types.proto;

public interface SharedAlbumOptionsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.photos.types.SharedAlbumOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * True if the shared album allows collaborators (users who have joined
   * the album) to add media items to it. Defaults to false.
   * </pre>
   *
   * <code>bool is_collaborative = 1;</code>
   *
   * @return The isCollaborative.
   */
  boolean getIsCollaborative();

  /**
   *
   *
   * <pre>
   * True if the shared album allows collaborators (users who have joined the
   * album) to add comments to the album. Defaults to false.
   * </pre>
   *
   * <code>bool is_commentable = 2;</code>
   *
   * @return The isCommentable.
   */
  boolean getIsCommentable();
}
