// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/photos/types/media_item.proto

package com.google.photos.types.proto;

public interface VideoOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.photos.types.Video)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Brand of the camera with which the video was taken.
   * </pre>
   *
   * <code>string camera_make = 1;</code>
   *
   * @return The cameraMake.
   */
  java.lang.String getCameraMake();
  /**
   *
   *
   * <pre>
   * Brand of the camera with which the video was taken.
   * </pre>
   *
   * <code>string camera_make = 1;</code>
   *
   * @return The bytes for cameraMake.
   */
  com.google.protobuf.ByteString getCameraMakeBytes();

  /**
   *
   *
   * <pre>
   * Model of the camera with which the video was taken.
   * </pre>
   *
   * <code>string camera_model = 2;</code>
   *
   * @return The cameraModel.
   */
  java.lang.String getCameraModel();
  /**
   *
   *
   * <pre>
   * Model of the camera with which the video was taken.
   * </pre>
   *
   * <code>string camera_model = 2;</code>
   *
   * @return The bytes for cameraModel.
   */
  com.google.protobuf.ByteString getCameraModelBytes();

  /**
   *
   *
   * <pre>
   * Frame rate of the video.
   * </pre>
   *
   * <code>double fps = 3;</code>
   *
   * @return The fps.
   */
  double getFps();

  /**
   *
   *
   * <pre>
   * Processing status of the video.
   * </pre>
   *
   * <code>.google.photos.types.VideoProcessingStatus status = 4;</code>
   *
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   *
   *
   * <pre>
   * Processing status of the video.
   * </pre>
   *
   * <code>.google.photos.types.VideoProcessingStatus status = 4;</code>
   *
   * @return The status.
   */
  com.google.photos.types.proto.VideoProcessingStatus getStatus();
}
