name: Gradle

on: [push, pull_request]

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['11', '17'] # todo: Add support for building with JDK 21 (will require Gradle 9)

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Gradle Check
        run: ./gradlew check --no-daemon

      - name: Gradle allJars
        run: ./gradlew allJars --no-daemon
